use lazy_static::lazy_static;
use std::{collections::HashMap, fmt::Display};

#[derive(Hash, Debug, Clone, PartialEq, Eq)]
pub enum AdrMode {
    IMPL, IMM, ABS,
    ABSX, ABSY,
    ZP, ZPX, ZPY,
    IND, INDX, INDY,
    REL
}

#[derive(Hash, Debug, Clone, PartialEq, Eq)]
pub enum Instr {
    LDA, LDX, LDY, 
    STA, STX, STY,
    TAX, TAY, TSX, TXA, TXS, TYA,
    PHA, PHP, PLA, PLP, 
    DEC, DEX, DEY, 
    INC, INX, INY, 
    ADC, SBC, 
    AND, EOR, ORA, 
    ASL, LSR, 
    ROL, ROR, 
    CLC, CLD, CLI, CLV, 
    SEC, SED, SEI, 
    CMP, CPX, CPY,
    BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS, 
    JMP, JSR, RTS, 
    BRK, RTI, 
    BIT, NOP,

    // unofficial instructions
    STP, SLO, ANC, RLA, SRE, ALR, RRA, ARR, SAX,
    XAA, AHX, TAS, SHY, SHX, LAX, LAS, DCP, AXS,
    ISC
}

impl Display for Instr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Hash, Debug, Clone, PartialEq, Eq)]
pub struct Opcode {
    pub hex: u8,
    pub official: bool,
    pub examples: Vec<String>
}

impl Opcode {
    fn new(hex: u8, official: bool, examples: Vec<String>) -> Self {
        Self {
            hex,
            official,
            examples
        }
    }
}


// https://github.com/afmika/opcodes-json-6502
lazy_static! {
    pub static ref INSTR: HashMap<String, Instr> = HashMap::from([
        ("LDA".to_owned(), Instr::LDA),
        ("LDX".to_owned(), Instr::LDX),
        ("LDY".to_owned(), Instr::LDY),
        ("STA".to_owned(), Instr::STA),
        ("STX".to_owned(), Instr::STX),
        ("STY".to_owned(), Instr::STY),
        ("TAX".to_owned(), Instr::TAX),
        ("TAY".to_owned(), Instr::TAY),
        ("TSX".to_owned(), Instr::TSX),
        ("TXA".to_owned(), Instr::TXA),
        ("TXS".to_owned(), Instr::TXS),
        ("TYA".to_owned(), Instr::TYA),
        ("PHA".to_owned(), Instr::PHA),
        ("PHP".to_owned(), Instr::PHP),
        ("PLA".to_owned(), Instr::PLA),
        ("PLP".to_owned(), Instr::PLP),
        ("DEC".to_owned(), Instr::DEC),
        ("DEX".to_owned(), Instr::DEX),
        ("DEY".to_owned(), Instr::DEY),
        ("INC".to_owned(), Instr::INC),
        ("INX".to_owned(), Instr::INX),
        ("INY".to_owned(), Instr::INY),
        ("ADC".to_owned(), Instr::ADC),
        ("SBC".to_owned(), Instr::SBC),
        ("AND".to_owned(), Instr::AND),
        ("EOR".to_owned(), Instr::EOR),
        ("ORA".to_owned(), Instr::ORA),
        ("ASL".to_owned(), Instr::ASL),
        ("LSR".to_owned(), Instr::LSR),
        ("ROL".to_owned(), Instr::ROL),
        ("ROR".to_owned(), Instr::ROR),
        ("CLC".to_owned(), Instr::CLC),
        ("CLD".to_owned(), Instr::CLD),
        ("CLI".to_owned(), Instr::CLI),
        ("CLV".to_owned(), Instr::CLV),
        ("SEC".to_owned(), Instr::SEC),
        ("SED".to_owned(), Instr::SED),
        ("SEI".to_owned(), Instr::SEI),
        ("CMP".to_owned(), Instr::CMP),
        ("CPX".to_owned(), Instr::CPX),
        ("CPY".to_owned(), Instr::CPY),
        ("BCC".to_owned(), Instr::BCC),
        ("BCS".to_owned(), Instr::BCS),
        ("BEQ".to_owned(), Instr::BEQ),
        ("BMI".to_owned(), Instr::BMI),
        ("BNE".to_owned(), Instr::BNE),
        ("BPL".to_owned(), Instr::BPL),
        ("BVC".to_owned(), Instr::BVC),
        ("BVS".to_owned(), Instr::BVS),
        ("JMP".to_owned(), Instr::JMP),
        ("JSR".to_owned(), Instr::JSR),
        ("RTS".to_owned(), Instr::RTS),
        ("BRK".to_owned(), Instr::BRK),
        ("RTI".to_owned(), Instr::RTI),
        ("BIT".to_owned(), Instr::BIT),
        ("NOP".to_owned(), Instr::NOP),
        ("STP".to_owned(), Instr::STP),
        ("SLO".to_owned(), Instr::SLO),
        ("ANC".to_owned(), Instr::ANC),
        ("RLA".to_owned(), Instr::RLA),
        ("SRE".to_owned(), Instr::SRE),
        ("ALR".to_owned(), Instr::ALR),
        ("RRA".to_owned(), Instr::RRA),
        ("ARR".to_owned(), Instr::ARR),
        ("SAX".to_owned(), Instr::SAX),
        ("XAA".to_owned(), Instr::XAA),
        ("AHX".to_owned(), Instr::AHX),
        ("TAS".to_owned(), Instr::TAS),
        ("SHY".to_owned(), Instr::SHY),
        ("SHX".to_owned(), Instr::SHX),
        ("LAX".to_owned(), Instr::LAX),
        ("LAS".to_owned(), Instr::LAS),
        ("DCP".to_owned(), Instr::DCP),
        ("AXS".to_owned(), Instr::AXS),
        ("ISC".to_owned(), Instr::ISC)
    ]);

    pub static ref OPCODES: HashMap<(Instr, AdrMode), Vec<Opcode>> = HashMap::from([
        ((Instr::BRK, AdrMode::IMPL), vec![Opcode::new(0x00, true, vec!["BRK".to_owned()])]),
        ((Instr::ORA, AdrMode::INDX), vec![Opcode::new(0x01, false, vec!["ORA ($BB,X)".to_owned()])]),
        ((Instr::ORA, AdrMode::ZP), vec![Opcode::new(0x05, false, vec!["ORA $BB".to_owned()])]),
        ((Instr::ORA, AdrMode::IMM), vec![Opcode::new(0x09, false, vec!["ORA #$BB".to_owned()])]),
        ((Instr::ORA, AdrMode::ABS), vec![Opcode::new(0x0D, false, vec!["ORA $LLHH".to_owned()])]),
        ((Instr::ORA, AdrMode::INDY), vec![Opcode::new(0x11, true, vec!["ORA ($BB),Y".to_owned()])]),
        ((Instr::ORA, AdrMode::ZPX), vec![Opcode::new(0x15, false, vec!["ORA $BB,X".to_owned()])]),
        ((Instr::ORA, AdrMode::ABSY), vec![Opcode::new(0x19, false, vec!["ORA $LLHH,Y".to_owned()])]),
        ((Instr::ORA, AdrMode::ABSX), vec![Opcode::new(0x1D, false, vec!["ORA $LLHH,X".to_owned()])]),
        ((Instr::STP, AdrMode::IMPL), vec![
            Opcode::new(0x02, false, vec!["STP".to_owned()]),
            Opcode::new(0x12, false, vec!["STP".to_owned()]),
            Opcode::new(0x22, false, vec!["STP".to_owned()]),
            Opcode::new(0x32, false, vec!["STP".to_owned()]),
            Opcode::new(0x42, false, vec!["STP".to_owned()]),
            Opcode::new(0x52, false, vec!["STP".to_owned()]),
            Opcode::new(0x62, false, vec!["STP".to_owned()]),
            Opcode::new(0x72, false, vec!["STP".to_owned()]),
            Opcode::new(0x92, false, vec!["STP".to_owned()]),
            Opcode::new(0xB2, false, vec!["STP".to_owned()]),
            Opcode::new(0xD2, false, vec!["STP".to_owned()]),
            Opcode::new(0xF2, false, vec!["STP".to_owned()])
        ]),
        ((Instr::SLO, AdrMode::INDX), vec![Opcode::new(0x03, false, vec!["SLO ($BB,X)".to_owned()])]),
        ((Instr::SLO, AdrMode::ZP), vec![Opcode::new(0x07, false, vec!["SLO $BB".to_owned()])]),
        ((Instr::SLO, AdrMode::ABS), vec![Opcode::new(0x0F, false, vec!["SLO $LLHH".to_owned()])]),
        ((Instr::SLO, AdrMode::INDY), vec![Opcode::new(0x13, false, vec!["SLO ($BB),Y".to_owned()])]),
        ((Instr::SLO, AdrMode::ZPX), vec![Opcode::new(0x17, false, vec!["SLO $BB,X".to_owned()])]),
        ((Instr::SLO, AdrMode::ABSY), vec![Opcode::new(0x1B, false, vec!["SLO $LLHH,Y".to_owned()])]),
        ((Instr::SLO, AdrMode::ABSX), vec![Opcode::new(0x1F, false, vec!["SLO $LLHH,X".to_owned()])]),
        ((Instr::NOP, AdrMode::ZP), vec![
            Opcode::new(0x04, false, vec!["NOP $BB".to_owned()]),
            Opcode::new(0x44, false, vec!["NOP $BB".to_owned()]),
            Opcode::new(0x64, false, vec!["NOP $BB".to_owned()])
        ]),
        ((Instr::NOP, AdrMode::ABS), vec![Opcode::new(0x0C, false, vec!["NOP $LLHH".to_owned()])]),
        ((Instr::NOP, AdrMode::ZPX), vec![
            Opcode::new(0x14, false, vec!["NOP $BB,X".to_owned()]),
            Opcode::new(0x34, false, vec!["NOP $BB,X".to_owned()]),
            Opcode::new(0x54, false, vec!["NOP $BB,X".to_owned()]),
            Opcode::new(0x74, false, vec!["NOP $BB,X".to_owned()]),
            Opcode::new(0xD4, false, vec!["NOP $BB,X".to_owned()]),
            Opcode::new(0xF4, false, vec!["NOP $BB,X".to_owned()])
        ]),
        ((Instr::NOP, AdrMode::IMPL), vec![
            Opcode::new(0x1A, false, vec!["NOP".to_owned()]),
            Opcode::new(0x3A, false, vec!["NOP".to_owned()]),
            Opcode::new(0x5A, false, vec!["NOP".to_owned()]),
            Opcode::new(0x7A, false, vec!["NOP".to_owned()]),
            Opcode::new(0xDA, false, vec!["NOP".to_owned()]),
            Opcode::new(0xEA, true, vec!["NOP".to_owned()]),
            Opcode::new(0xFA, false, vec!["NOP".to_owned()])
        ]),
        ((Instr::NOP, AdrMode::ABSX), vec![
            Opcode::new(0x1C, false, vec!["NOP $LLHH,X".to_owned()]),
            Opcode::new(0x3C, false, vec!["NOP $LLHH,X".to_owned()]),
            Opcode::new(0x5C, false, vec!["NOP $LLHH,X".to_owned()]),
            Opcode::new(0x7C, false, vec!["NOP $LLHH,X".to_owned()]),
            Opcode::new(0xDC, false, vec!["NOP $LLHH,X".to_owned()]),
            Opcode::new(0xFC, false, vec!["NOP $LLHH,X".to_owned()])
        ]),
        ((Instr::NOP, AdrMode::IMM), vec![
            Opcode::new(0x80, false, vec!["NOP #$BB".to_owned()]),
            Opcode::new(0x82, false, vec!["NOP #$BB".to_owned()]),
            Opcode::new(0x89, false, vec!["NOP #$BB".to_owned()]),
            Opcode::new(0xC2, false, vec!["NOP #$BB".to_owned()]),
            Opcode::new(0xE2, false, vec!["NOP #$BB".to_owned()])
        ]),
        ((Instr::ASL, AdrMode::ZP), vec![Opcode::new(0x06, false, vec!["ASL $BB".to_owned()])]),
        ((Instr::ASL, AdrMode::IMPL), vec![Opcode::new(0x0A, false, vec!["ASL".to_owned()])]),
        ((Instr::ASL, AdrMode::ABS), vec![Opcode::new(0x0E, false, vec!["ASL $LLHH".to_owned()])]),
        ((Instr::ASL, AdrMode::ZPX), vec![Opcode::new(0x16, false, vec!["ASL $BB,X".to_owned()])]),
        ((Instr::ASL, AdrMode::ABSX), vec![Opcode::new(0x1E, true, vec!["ASL $LLHH,X".to_owned()])]),
        ((Instr::PHP, AdrMode::IMPL), vec![Opcode::new(0x08, true, vec!["PHP".to_owned()])]),
        ((Instr::ANC, AdrMode::IMM), vec![
            Opcode::new(0x0B, false, vec!["ANC #$BB".to_owned()]),
            Opcode::new(0x2B, false, vec!["ANC #$BB".to_owned()])
        ]),
        ((Instr::BPL, AdrMode::REL), vec![Opcode::new(0x10, true, vec!["BPL $BB".to_owned(), "BPL label".to_owned()])]),
        ((Instr::CLC, AdrMode::IMPL), vec![Opcode::new(0x18, true, vec!["CLC".to_owned()])]),
        ((Instr::JSR, AdrMode::ABS), vec![Opcode::new(0x20, true, vec!["JSR $LLHH".to_owned()])]),
        ((Instr::AND, AdrMode::INDX), vec![Opcode::new(0x21, false, vec!["AND ($BB,X)".to_owned()])]),
        ((Instr::AND, AdrMode::ZP), vec![Opcode::new(0x25, false, vec!["AND $BB".to_owned()])]),
        ((Instr::AND, AdrMode::IMM), vec![Opcode::new(0x29, false, vec!["AND #$BB".to_owned()])]),
        ((Instr::AND, AdrMode::ABS), vec![Opcode::new(0x2D, false, vec!["AND $LLHH".to_owned()])]),
        ((Instr::AND, AdrMode::INDY), vec![Opcode::new(0x31, true, vec!["AND ($BB),Y".to_owned()])]),
        ((Instr::AND, AdrMode::ZPX), vec![Opcode::new(0x35, false, vec!["AND $BB,X".to_owned()])]),
        ((Instr::AND, AdrMode::ABSY), vec![Opcode::new(0x39, false, vec!["AND $LLHH,Y".to_owned()])]),
        ((Instr::AND, AdrMode::ABSX), vec![Opcode::new(0x3D, false, vec!["AND $LLHH,X".to_owned()])]),
        ((Instr::RLA, AdrMode::INDX), vec![Opcode::new(0x23, false, vec!["RLA ($BB,X)".to_owned()])]),
        ((Instr::RLA, AdrMode::ZP), vec![Opcode::new(0x27, false, vec!["RLA $BB".to_owned()])]),
        ((Instr::RLA, AdrMode::ABS), vec![Opcode::new(0x2F, false, vec!["RLA $LLHH".to_owned()])]),
        ((Instr::RLA, AdrMode::INDY), vec![Opcode::new(0x33, false, vec!["RLA ($BB),Y".to_owned()])]),
        ((Instr::RLA, AdrMode::ZPX), vec![Opcode::new(0x37, false, vec!["RLA $BB,X".to_owned()])]),
        ((Instr::RLA, AdrMode::ABSY), vec![Opcode::new(0x3B, false, vec!["RLA $LLHH,Y".to_owned()])]),
        ((Instr::RLA, AdrMode::ABSX), vec![Opcode::new(0x3F, false, vec!["RLA $LLHH,X".to_owned()])]),
        ((Instr::BIT, AdrMode::ZP), vec![Opcode::new(0x24, false, vec!["BIT $BB".to_owned()])]),
        ((Instr::BIT, AdrMode::ABS), vec![Opcode::new(0x2C, true, vec!["BIT $LLHH".to_owned()])]),
        ((Instr::ROL, AdrMode::ZP), vec![Opcode::new(0x26, false, vec!["ROL $BB".to_owned()])]),
        ((Instr::ROL, AdrMode::IMPL), vec![Opcode::new(0x2A, false, vec!["ROL".to_owned()])]),
        ((Instr::ROL, AdrMode::ABS), vec![Opcode::new(0x2E, false, vec!["ROL $LLHH".to_owned()])]),
        ((Instr::ROL, AdrMode::ZPX), vec![Opcode::new(0x36, false, vec!["ROL $BB,X".to_owned()])]),
        ((Instr::ROL, AdrMode::ABSX), vec![Opcode::new(0x3E, true, vec!["ROL $LLHH,X".to_owned()])]),
        ((Instr::PLP, AdrMode::IMPL), vec![Opcode::new(0x28, true, vec!["PLP".to_owned()])]),
        ((Instr::BMI, AdrMode::REL), vec![Opcode::new(0x30, true, vec!["BMI $BB".to_owned(), "BMI label".to_owned()])]),
        ((Instr::SEC, AdrMode::IMPL), vec![Opcode::new(0x38, true, vec!["SEC".to_owned()])]),
        ((Instr::RTI, AdrMode::IMPL), vec![Opcode::new(0x40, true, vec!["RTI".to_owned()])]),
        ((Instr::EOR, AdrMode::INDX), vec![Opcode::new(0x41, false, vec!["EOR ($BB,X)".to_owned()])]),
        ((Instr::EOR, AdrMode::ZP), vec![Opcode::new(0x45, false, vec!["EOR $BB".to_owned()])]),
        ((Instr::EOR, AdrMode::IMM), vec![Opcode::new(0x49, false, vec!["EOR #$BB".to_owned()])]),
        ((Instr::EOR, AdrMode::ABS), vec![Opcode::new(0x4D, false, vec!["EOR $LLHH".to_owned()])]),
        ((Instr::EOR, AdrMode::INDY), vec![Opcode::new(0x51, true, vec!["EOR ($BB),Y".to_owned()])]),
        ((Instr::EOR, AdrMode::ZPX), vec![Opcode::new(0x55, false, vec!["EOR $BB,X".to_owned()])]),
        ((Instr::EOR, AdrMode::ABSY), vec![Opcode::new(0x59, false, vec!["EOR $LLHH,Y".to_owned()])]),
        ((Instr::EOR, AdrMode::ABSX), vec![Opcode::new(0x5D, false, vec!["EOR $LLHH,X".to_owned()])]),
        ((Instr::SRE, AdrMode::INDX), vec![Opcode::new(0x43, false, vec!["SRE ($BB,X)".to_owned()])]),
        ((Instr::SRE, AdrMode::ZP), vec![Opcode::new(0x47, false, vec!["SRE $BB".to_owned()])]),
        ((Instr::SRE, AdrMode::ABS), vec![Opcode::new(0x4F, false, vec!["SRE $LLHH".to_owned()])]),
        ((Instr::SRE, AdrMode::INDY), vec![Opcode::new(0x53, false, vec!["SRE ($BB),Y".to_owned()])]),
        ((Instr::SRE, AdrMode::ZPX), vec![Opcode::new(0x57, false, vec!["SRE $BB,X".to_owned()])]),
        ((Instr::SRE, AdrMode::ABSY), vec![Opcode::new(0x5B, false, vec!["SRE $LLHH,Y".to_owned()])]),
        ((Instr::SRE, AdrMode::ABSX), vec![Opcode::new(0x5F, false, vec!["SRE $LLHH,X".to_owned()])]),
        ((Instr::LSR, AdrMode::ZP), vec![Opcode::new(0x46, false, vec!["LSR $BB".to_owned()])]),
        ((Instr::LSR, AdrMode::IMPL), vec![Opcode::new(0x4A, false, vec!["LSR".to_owned()])]),
        ((Instr::LSR, AdrMode::ABS), vec![Opcode::new(0x4E, false, vec!["LSR $LLHH".to_owned()])]),
        ((Instr::LSR, AdrMode::ZPX), vec![Opcode::new(0x56, false, vec!["LSR $BB,X".to_owned()])]),
        ((Instr::LSR, AdrMode::ABSX), vec![Opcode::new(0x5E, true, vec!["LSR $LLHH,X".to_owned()])]),
        ((Instr::PHA, AdrMode::IMPL), vec![Opcode::new(0x48, true, vec!["PHA".to_owned()])]),
        ((Instr::ALR, AdrMode::IMM), vec![Opcode::new(0x4B, false, vec!["ALR #$BB".to_owned()])]),
        ((Instr::JMP, AdrMode::ABS), vec![Opcode::new(0x4C, false, vec!["JMP $LLHH".to_owned()])]),
        ((Instr::JMP, AdrMode::IND), vec![Opcode::new(0x6C, true, vec!["JMP ($LLHH)".to_owned()])]),
        ((Instr::BVC, AdrMode::REL), vec![Opcode::new(0x50, true, vec!["BVC $BB".to_owned(), "BVC label".to_owned()])]),
        ((Instr::CLI, AdrMode::IMPL), vec![Opcode::new(0x58, true, vec!["CLI".to_owned()])]),
        ((Instr::RTS, AdrMode::IMPL), vec![Opcode::new(0x60, true, vec!["RTS".to_owned()])]),
        ((Instr::ADC, AdrMode::INDX), vec![Opcode::new(0x61, false, vec!["ADC ($BB,X)".to_owned()])]),
        ((Instr::ADC, AdrMode::ZP), vec![Opcode::new(0x65, false, vec!["ADC $BB".to_owned()])]),
        ((Instr::ADC, AdrMode::IMM), vec![Opcode::new(0x69, false, vec!["ADC #$BB".to_owned()])]),
        ((Instr::ADC, AdrMode::ABS), vec![Opcode::new(0x6D, false, vec!["ADC $LLHH".to_owned()])]),
        ((Instr::ADC, AdrMode::INDY), vec![Opcode::new(0x71, true, vec!["ADC ($BB),Y".to_owned()])]),
        ((Instr::ADC, AdrMode::ZPX), vec![Opcode::new(0x75, false, vec!["ADC $BB,X".to_owned()])]),
        ((Instr::ADC, AdrMode::ABSY), vec![Opcode::new(0x79, false, vec!["ADC $LLHH,Y".to_owned()])]),
        ((Instr::ADC, AdrMode::ABSX), vec![Opcode::new(0x7D, false, vec!["ADC $LLHH,X".to_owned()])]),
        ((Instr::RRA, AdrMode::INDX), vec![Opcode::new(0x63, false, vec!["RRA ($BB,X)".to_owned()])]),
        ((Instr::RRA, AdrMode::ZP), vec![Opcode::new(0x67, false, vec!["RRA $BB".to_owned()])]),
        ((Instr::RRA, AdrMode::ABS), vec![Opcode::new(0x6F, false, vec!["RRA $LLHH".to_owned()])]),
        ((Instr::RRA, AdrMode::INDY), vec![Opcode::new(0x73, false, vec!["RRA ($BB),Y".to_owned()])]),
        ((Instr::RRA, AdrMode::ZPX), vec![Opcode::new(0x77, false, vec!["RRA $BB,X".to_owned()])]),
        ((Instr::RRA, AdrMode::ABSY), vec![Opcode::new(0x7B, false, vec!["RRA $LLHH,Y".to_owned()])]),
        ((Instr::RRA, AdrMode::ABSX), vec![Opcode::new(0x7F, false, vec!["RRA $LLHH,X".to_owned()])]),
        ((Instr::ROR, AdrMode::ZP), vec![Opcode::new(0x66, false, vec!["ROR $BB".to_owned()])]),
        ((Instr::ROR, AdrMode::IMPL), vec![Opcode::new(0x6A, false, vec!["ROR".to_owned()])]),
        ((Instr::ROR, AdrMode::ABS), vec![Opcode::new(0x6E, false, vec!["ROR $LLHH".to_owned()])]),
        ((Instr::ROR, AdrMode::ZPX), vec![Opcode::new(0x76, false, vec!["ROR $BB,X".to_owned()])]),
        ((Instr::ROR, AdrMode::ABSX), vec![Opcode::new(0x7E, true, vec!["ROR $LLHH,X".to_owned()])]),
        ((Instr::PLA, AdrMode::IMPL), vec![Opcode::new(0x68, true, vec!["PLA".to_owned()])]),
        ((Instr::ARR, AdrMode::IMM), vec![Opcode::new(0x6B, false, vec!["ARR #$BB".to_owned()])]),
        ((Instr::BVS, AdrMode::REL), vec![Opcode::new(0x70, true, vec!["BVS $BB".to_owned(), "BVS label".to_owned()])]),
        ((Instr::SEI, AdrMode::IMPL), vec![Opcode::new(0x78, true, vec!["SEI".to_owned()])]),
        ((Instr::STA, AdrMode::INDX), vec![Opcode::new(0x81, false, vec!["STA ($BB,X)".to_owned()])]),
        ((Instr::STA, AdrMode::ZP), vec![Opcode::new(0x85, false, vec!["STA $BB".to_owned()])]),
        ((Instr::STA, AdrMode::ABS), vec![Opcode::new(0x8D, false, vec!["STA $LLHH".to_owned()])]),
        ((Instr::STA, AdrMode::INDY), vec![Opcode::new(0x91, true, vec!["STA ($BB),Y".to_owned()])]),
        ((Instr::STA, AdrMode::ZPX), vec![Opcode::new(0x95, false, vec!["STA $BB,X".to_owned()])]),
        ((Instr::STA, AdrMode::ABSY), vec![Opcode::new(0x99, false, vec!["STA $LLHH,Y".to_owned()])]),
        ((Instr::STA, AdrMode::ABSX), vec![Opcode::new(0x9D, false, vec!["STA $LLHH,X".to_owned()])]),
        ((Instr::SAX, AdrMode::INDX), vec![Opcode::new(0x83, false, vec!["SAX ($BB,X)".to_owned()])]),
        ((Instr::SAX, AdrMode::ZP), vec![Opcode::new(0x87, false, vec!["SAX $BB".to_owned()])]),
        ((Instr::SAX, AdrMode::ABS), vec![Opcode::new(0x8F, false, vec!["SAX $LLHH".to_owned()])]),
        ((Instr::SAX, AdrMode::ZPY), vec![Opcode::new(0x97, false, vec!["SAX $BB,Y".to_owned()])]),
        ((Instr::STY, AdrMode::ZP), vec![Opcode::new(0x84, false, vec!["STY $BB".to_owned()])]),
        ((Instr::STY, AdrMode::ABS), vec![Opcode::new(0x8C, true, vec!["STY $LLHH".to_owned()])]),
        ((Instr::STY, AdrMode::ZPX), vec![Opcode::new(0x94, false, vec!["STY $BB,X".to_owned()])]),
        ((Instr::STX, AdrMode::ZP), vec![Opcode::new(0x86, false, vec!["STX $BB".to_owned()])]),
        ((Instr::STX, AdrMode::ABS), vec![Opcode::new(0x8E, true, vec!["STX $LLHH".to_owned()])]),
        ((Instr::STX, AdrMode::ZPY), vec![Opcode::new(0x96, false, vec!["STX $BB,Y".to_owned()])]),
        ((Instr::DEY, AdrMode::IMPL), vec![Opcode::new(0x88, true, vec!["DEY".to_owned()])]),
        ((Instr::TXA, AdrMode::IMPL), vec![Opcode::new(0x8A, true, vec!["TXA".to_owned()])]),
        ((Instr::XAA, AdrMode::IMM), vec![Opcode::new(0x8B, false, vec!["XAA #$BB".to_owned()])]),
        ((Instr::BCC, AdrMode::REL), vec![Opcode::new(0x90, true, vec!["BCC $BB".to_owned(), "BCC label".to_owned()])]),
        ((Instr::AHX, AdrMode::INDY), vec![Opcode::new(0x93, false, vec!["AHX ($BB),Y".to_owned()])]),
        ((Instr::AHX, AdrMode::ABSY), vec![Opcode::new(0x9F, false, vec!["AHX $LLHH,Y".to_owned()])]),
        ((Instr::TYA, AdrMode::IMPL), vec![Opcode::new(0x98, true, vec!["TYA".to_owned()])]),
        ((Instr::TXS, AdrMode::IMPL), vec![Opcode::new(0x9A, true, vec!["TXS".to_owned()])]),
        ((Instr::TAS, AdrMode::ABSY), vec![Opcode::new(0x9B, false, vec!["TAS $LLHH,Y".to_owned()])]),
        ((Instr::SHY, AdrMode::ABSX), vec![Opcode::new(0x9C, false, vec!["SHY $LLHH,X".to_owned()])]),
        ((Instr::SHX, AdrMode::ABSY), vec![Opcode::new(0x9E, false, vec!["SHX $LLHH,Y".to_owned()])]),
        ((Instr::LDY, AdrMode::IMM), vec![Opcode::new(0xA0, false, vec!["LDY #$BB".to_owned()])]),
        ((Instr::LDY, AdrMode::ZP), vec![Opcode::new(0xA4, false, vec!["LDY $BB".to_owned()])]),
        ((Instr::LDY, AdrMode::ABS), vec![Opcode::new(0xAC, false, vec!["LDY $LLHH".to_owned()])]),
        ((Instr::LDY, AdrMode::ZPX), vec![Opcode::new(0xB4, false, vec!["LDY $BB,X".to_owned()])]),
        ((Instr::LDY, AdrMode::ABSX), vec![Opcode::new(0xBC, true, vec!["LDY $LLHH,X".to_owned()])]),
        ((Instr::LDA, AdrMode::INDX), vec![Opcode::new(0xA1, false, vec!["LDA ($BB,X)".to_owned()])]),
        ((Instr::LDA, AdrMode::ZP), vec![Opcode::new(0xA5, false, vec!["LDA $BB".to_owned()])]),
        ((Instr::LDA, AdrMode::IMM), vec![Opcode::new(0xA9, false, vec!["LDA #$BB".to_owned()])]),
        ((Instr::LDA, AdrMode::ABS), vec![Opcode::new(0xAD, false, vec!["LDA $LLHH".to_owned()])]),
        ((Instr::LDA, AdrMode::INDY), vec![Opcode::new(0xB1, true, vec!["LDA ($BB),Y".to_owned()])]),
        ((Instr::LDA, AdrMode::ZPX), vec![Opcode::new(0xB5, false, vec!["LDA $BB,X".to_owned()])]),
        ((Instr::LDA, AdrMode::ABSY), vec![Opcode::new(0xB9, false, vec!["LDA $LLHH,Y".to_owned()])]),
        ((Instr::LDA, AdrMode::ABSX), vec![Opcode::new(0xBD, false, vec!["LDA $LLHH,X".to_owned()])]),
        ((Instr::LDX, AdrMode::IMM), vec![Opcode::new(0xA2, false, vec!["LDX #$BB".to_owned()])]),
        ((Instr::LDX, AdrMode::ZP), vec![Opcode::new(0xA6, false, vec!["LDX $BB".to_owned()])]),
        ((Instr::LDX, AdrMode::ABS), vec![Opcode::new(0xAE, false, vec!["LDX $LLHH".to_owned()])]),
        ((Instr::LDX, AdrMode::ZPY), vec![Opcode::new(0xB6, false, vec!["LDX $BB,Y".to_owned()])]),
        ((Instr::LDX, AdrMode::ABSY), vec![Opcode::new(0xBE, true, vec!["LDX $LLHH,Y".to_owned()])]),
        ((Instr::LAX, AdrMode::INDX), vec![Opcode::new(0xA3, false, vec!["LAX ($BB,X)".to_owned()])]),
        ((Instr::LAX, AdrMode::ZP), vec![Opcode::new(0xA7, false, vec!["LAX $BB".to_owned()])]),
        ((Instr::LAX, AdrMode::IMM), vec![Opcode::new(0xAB, false, vec!["LAX #$BB".to_owned()])]),
        ((Instr::LAX, AdrMode::ABS), vec![Opcode::new(0xAF, false, vec!["LAX $LLHH".to_owned()])]),
        ((Instr::LAX, AdrMode::INDY), vec![Opcode::new(0xB3, false, vec!["LAX ($BB),Y".to_owned()])]),
        ((Instr::LAX, AdrMode::ZPY), vec![Opcode::new(0xB7, false, vec!["LAX $BB,Y".to_owned()])]),
        ((Instr::LAX, AdrMode::ABSY), vec![Opcode::new(0xBF, false, vec!["LAX $LLHH,Y".to_owned()])]),
        ((Instr::TAY, AdrMode::IMPL), vec![Opcode::new(0xA8, true, vec!["TAY".to_owned()])]),
        ((Instr::TAX, AdrMode::IMPL), vec![Opcode::new(0xAA, true, vec!["TAX".to_owned()])]),
        ((Instr::BCS, AdrMode::REL), vec![Opcode::new(0xB0, true, vec!["BCS $BB".to_owned(), "BCS label".to_owned()])]),
        ((Instr::CLV, AdrMode::IMPL), vec![Opcode::new(0xB8, true, vec!["CLV".to_owned()])]),
        ((Instr::TSX, AdrMode::IMPL), vec![Opcode::new(0xBA, true, vec!["TSX".to_owned()])]),
        ((Instr::LAS, AdrMode::ABSY), vec![Opcode::new(0xBB, false, vec!["LAS $LLHH,Y".to_owned()])]),
        ((Instr::CPY, AdrMode::IMM), vec![Opcode::new(0xC0, false, vec!["CPY #$BB".to_owned()])]),
        ((Instr::CPY, AdrMode::ZP), vec![Opcode::new(0xC4, false, vec!["CPY $BB".to_owned()])]),
        ((Instr::CPY, AdrMode::ABS), vec![Opcode::new(0xCC, true, vec!["CPY $LLHH".to_owned()])]),
        ((Instr::CMP, AdrMode::INDX), vec![Opcode::new(0xC1, false, vec!["CMP ($BB,X)".to_owned()])]),
        ((Instr::CMP, AdrMode::ZP), vec![Opcode::new(0xC5, false, vec!["CMP $BB".to_owned()])]),
        ((Instr::CMP, AdrMode::IMM), vec![Opcode::new(0xC9, false, vec!["CMP #$BB".to_owned()])]),
        ((Instr::CMP, AdrMode::ABS), vec![Opcode::new(0xCD, false, vec!["CMP $LLHH".to_owned()])]),
        ((Instr::CMP, AdrMode::INDY), vec![Opcode::new(0xD1, true, vec!["CMP ($BB),Y".to_owned()])]),
        ((Instr::CMP, AdrMode::ZPX), vec![Opcode::new(0xD5, false, vec!["CMP $BB,X".to_owned()])]),
        ((Instr::CMP, AdrMode::ABSY), vec![Opcode::new(0xD9, false, vec!["CMP $LLHH,Y".to_owned()])]),
        ((Instr::CMP, AdrMode::ABSX), vec![Opcode::new(0xDD, false, vec!["CMP $LLHH,X".to_owned()])]),
        ((Instr::DCP, AdrMode::INDX), vec![Opcode::new(0xC3, false, vec!["DCP ($BB,X)".to_owned()])]),
        ((Instr::DCP, AdrMode::ZP), vec![Opcode::new(0xC7, false, vec!["DCP $BB".to_owned()])]),
        ((Instr::DCP, AdrMode::ABS), vec![Opcode::new(0xCF, false, vec!["DCP $LLHH".to_owned()])]),
        ((Instr::DCP, AdrMode::INDY), vec![Opcode::new(0xD3, false, vec!["DCP ($BB),Y".to_owned()])]),
        ((Instr::DCP, AdrMode::ZPX), vec![Opcode::new(0xD7, false, vec!["DCP $BB,X".to_owned()])]),
        ((Instr::DCP, AdrMode::ABSY), vec![Opcode::new(0xDB, false, vec!["DCP $LLHH,Y".to_owned()])]),
        ((Instr::DCP, AdrMode::ABSX), vec![Opcode::new(0xDF, false, vec!["DCP $LLHH,X".to_owned()])]),
        ((Instr::DEC, AdrMode::ZP), vec![Opcode::new(0xC6, false, vec!["DEC $BB".to_owned()])]),
        ((Instr::DEC, AdrMode::ABS), vec![Opcode::new(0xCE, false, vec!["DEC $LLHH".to_owned()])]),
        ((Instr::DEC, AdrMode::ZPX), vec![Opcode::new(0xD6, false, vec!["DEC $BB,X".to_owned()])]),
        ((Instr::DEC, AdrMode::ABSX), vec![Opcode::new(0xDE, true, vec!["DEC $LLHH,X".to_owned()])]),
        ((Instr::INY, AdrMode::IMPL), vec![Opcode::new(0xC8, true, vec!["INY".to_owned()])]),
        ((Instr::DEX, AdrMode::IMPL), vec![Opcode::new(0xCA, true, vec!["DEX".to_owned()])]),
        ((Instr::AXS, AdrMode::IMM), vec![Opcode::new(0xCB, false, vec!["AXS #$BB".to_owned()])]),
        ((Instr::BNE, AdrMode::REL), vec![Opcode::new(0xD0, true, vec!["BNE $BB".to_owned(), "BNE label".to_owned()])]),
        ((Instr::CLD, AdrMode::IMPL), vec![Opcode::new(0xD8, true, vec!["CLD".to_owned()])]),
        ((Instr::CPX, AdrMode::IMM), vec![Opcode::new(0xE0, false, vec!["CPX #$BB".to_owned()])]),
        ((Instr::CPX, AdrMode::ZP), vec![Opcode::new(0xE4, false, vec!["CPX $BB".to_owned()])]),
        ((Instr::CPX, AdrMode::ABS), vec![Opcode::new(0xEC, true, vec!["CPX $LLHH".to_owned()])]),
        ((Instr::SBC, AdrMode::INDX), vec![Opcode::new(0xE1, false, vec!["SBC ($BB,X)".to_owned()])]),
        ((Instr::SBC, AdrMode::ZP), vec![Opcode::new(0xE5, false, vec!["SBC $BB".to_owned()])]),
        ((Instr::SBC, AdrMode::IMM), vec![
            Opcode::new(0xE9, false, vec!["SBC #$BB".to_owned()]),
            Opcode::new(0xEB, false, vec!["SBC #$BB".to_owned()])
        ]),
        ((Instr::SBC, AdrMode::ABS), vec![Opcode::new(0xED, false, vec!["SBC $LLHH".to_owned()])]),
        ((Instr::SBC, AdrMode::INDY), vec![Opcode::new(0xF1, true, vec!["SBC ($BB),Y".to_owned()])]),
        ((Instr::SBC, AdrMode::ZPX), vec![Opcode::new(0xF5, false, vec!["SBC $BB,X".to_owned()])]),
        ((Instr::SBC, AdrMode::ABSY), vec![Opcode::new(0xF9, false, vec!["SBC $LLHH,Y".to_owned()])]),
        ((Instr::SBC, AdrMode::ABSX), vec![Opcode::new(0xFD, false, vec!["SBC $LLHH,X".to_owned()])]),
        ((Instr::ISC, AdrMode::INDX), vec![Opcode::new(0xE3, false, vec!["ISC ($BB,X)".to_owned()])]),
        ((Instr::ISC, AdrMode::ZP), vec![Opcode::new(0xE7, false, vec!["ISC $BB".to_owned()])]),
        ((Instr::ISC, AdrMode::ABS), vec![Opcode::new(0xEF, false, vec!["ISC $LLHH".to_owned()])]),
        ((Instr::ISC, AdrMode::INDY), vec![Opcode::new(0xF3, false, vec!["ISC ($BB),Y".to_owned()])]),
        ((Instr::ISC, AdrMode::ZPX), vec![Opcode::new(0xF7, false, vec!["ISC $BB,X".to_owned()])]),
        ((Instr::ISC, AdrMode::ABSY), vec![Opcode::new(0xFB, false, vec!["ISC $LLHH,Y".to_owned()])]),
        ((Instr::ISC, AdrMode::ABSX), vec![Opcode::new(0xFF, false, vec!["ISC $LLHH,X".to_owned()])]),
        ((Instr::INC, AdrMode::ZP), vec![Opcode::new(0xE6, false, vec!["INC $BB".to_owned()])]),
        ((Instr::INC, AdrMode::ABS), vec![Opcode::new(0xEE, false, vec!["INC $LLHH".to_owned()])]),
        ((Instr::INC, AdrMode::ZPX), vec![Opcode::new(0xF6, false, vec!["INC $BB,X".to_owned()])]),
        ((Instr::INC, AdrMode::ABSX), vec![Opcode::new(0xFE, true, vec!["INC $LLHH,X".to_owned()])]),
        ((Instr::INX, AdrMode::IMPL), vec![Opcode::new(0xE8, true, vec!["INX".to_owned()])]),
        ((Instr::BEQ, AdrMode::REL), vec![Opcode::new(0xF0, true, vec!["BEQ $BB".to_owned(), "BEQ label".to_owned()])]),
        ((Instr::SED, AdrMode::IMPL), vec![Opcode::new(0xF8, true, vec!["SED".to_owned()])]),
    ]);
}
